version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  express:
    depends_on:
      - mongodb
    build: ./nodejs-express-mongodb
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/gs
    volumes:
      - ./data:/data
      - ./nodejs-express-mongodb:/usr/src/app

  react:
    build: ./react-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/app
